version: '3'


services:
  db:
    image: postgres:14.3
    restart: always
    ports: 
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    container_name: chatbotdb
    volumes:
      - ./postgres:/var/lib/postgresql/data
